<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.classifieds_near_listings' => 'Classifieds: Nearby listings',
  'widget_def.classifieds_new_listings' => 'Classifieds: Latest listings',
  'widget_def.classifieds_user_feedback' => 'Classifieds: User feedback',
  'widget_def.dbt_ecom_latest_reviews' => 'DragonByte eCommerce: Latest reviews',
  'widget_def.dbt_ecom_new_products' => 'DragonByte eCommerce: New Products',
  'widget_def.dbt_ecom_rnd_products' => 'DragonByte eCommerce: Random Products',
  'widget_def.dbt_ecom_top_products' => 'DragonByte eCommerce: Top Rated Products',
  'widget_def.find_member' => 'Find member',
  'widget_def.forum_statistics' => 'Forum statistics',
  'widget_def.highestRatedInCategory' => 'Highest rated Item in Category',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Members online',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'New profile posts',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Newest members',
  'widget_def.online_statistics' => 'Online statistics',
  'widget_def.php_callback' => 'PHP callback',
  'widget_def.search_forum' => 'Search forum',
  'widget_def.share_page' => 'Share this page',
  'widget_def.snog_forms' => 'Form list',
  'widget_def.snog_forms_form' => 'Form',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.visitor_panel' => 'Visitor panel',
  'widget_def.xfrm_featured_resources' => 'XFRM: Featured resources',
  'widget_def.xfrm_latest_reviews' => 'XFRM: Latest reviews',
  'widget_def.xfrm_new_resources' => 'XFRM: New resources',
  'widget_def.xfrm_top_resources' => 'XFRM: Top resources',
);