<?php
return array(
    'permission_interface.ahGamerProfiles' => '[AH] Spelarprofiler',
    'permission_interface.bookmarkPermissions' => 'Bokmärksbehörigheter',
    'permission_interface.conversationModeratorPermissions' => 'Behörigheter för konversationsmoderator',
    'permission_interface.conversationPermissions' => 'Konversationsbehörigheter',
    'permission_interface.dbtechShop' => 'DragonByte Shop-behörigheter',
    'permission_interface.dbtechShopModerator' => 'DragonByte Shop moderator behörigheter',
    'permission_interface.dbtechShopTradePostModeratorPermissions' => 'DragonByte Shop handelspost moderator behörigheter',
    'permission_interface.dbtechShopTradePostPermissions' => 'DragonByte Shop handelspostbehörigheter',
    'permission_interface.forumModeratorPermissions' => 'Forum moderator behörigheter',
    'permission_interface.forumPermissions' => 'Forumbehörigheter',
    'permission_interface.generalModeratorPermissions' => 'Allmänna moderatorbehörigheter',
    'permission_interface.generalPermissions' => 'Allmänna behörigheter',
    'permission_interface.klUI' => '[TH] Behörigheter för användarförbättringar',
    'permission_interface.klUIModerator' => '[TH] Moderatorbehörigheter för användarförbättringar',
    'permission_interface.moveAndCreate' => '[XB] MoveCreateThreads',
    'permission_interface.postAttachmentPermissions' => 'Behörigheter för att lägga upp bifogade filer',
    'permission_interface.profilePostModeratorPermissions' => 'Behörigheter för moderator för profilinlägg',
    'permission_interface.profilePostPermissions' => 'Behörigheter för profilinlägg',
    'permission_interface.signaturePermissions' => 'Signaturbehörigheter',
    'permission_interface.siropuReferralContests' => 'Remisstävlingar',
    'permission_interface.sv_ForumRateLimiting' => 'Forum Begränsning',
    'permission_interface.th_uix' => 'UI.X-behörigheter',
    'permission_interface.tournament' => '[XB] Turnering',
    'permission_interface.xb_avatar_gallery' => '[XB] Avatargalleri',
    'permission_interface.xb_statics_grp' => '[XB] Falsk aktivitet',
);
